@baseUrl = https://localhost:5001

### Register
POST {{baseUrl}}/api/buggy/auth
Content-Type: application/json

{
  "displayName": "laur",
  "email": "laur@example.com",
  "password": "password"
}

### Login
POST {{baseUrl}}/api/accounts/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "P@ssw0rd!"
}
