@baseUrl = https://localhost:5001

### Register
POST {{baseUrl}}/api/accounts/register
Content-Type: application/json

{
  "displayName": "admin",
  "email": "admin@example.com",
  "password": "P@ssw0rd!"
}

### Login
POST {{baseUrl}}/api/accounts/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "P@ssw0rd!"
}
